version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfilenewrelic
    image: sandymadaan/php7.3-newrelic:0.5
    ports:
      - 8082:80
    volumes:
      - .:/var/www/html